// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASskUfS-vm7TTXh7Es1deYKEQt8ELYFRA',
    appId: '1:869633347200:web:453e8205c73e8b4b63a065',
    messagingSenderId: '869633347200',
    projectId: 'inventario-b125a',
    authDomain: 'inventario-b125a.firebaseapp.com',
    storageBucket: 'inventario-b125a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT0RD9D3J7l1zxTOdZO8kxFpxeP4EoGeI',
    appId: '1:869633347200:android:1c50b1c6864dee4463a065',
    messagingSenderId: '869633347200',
    projectId: 'inventario-b125a',
    storageBucket: 'inventario-b125a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCV8POiEWw8nZLb_2F43adp9UEDNf3Xa8',
    appId: '1:869633347200:ios:dfcdc6c3a581803063a065',
    messagingSenderId: '869633347200',
    projectId: 'inventario-b125a',
    storageBucket: 'inventario-b125a.firebasestorage.app',
    iosBundleId: 'com.example.diicsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCV8POiEWw8nZLb_2F43adp9UEDNf3Xa8',
    appId: '1:869633347200:ios:dfcdc6c3a581803063a065',
    messagingSenderId: '869633347200',
    projectId: 'inventario-b125a',
    storageBucket: 'inventario-b125a.firebasestorage.app',
    iosBundleId: 'com.example.diicsa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASskUfS-vm7TTXh7Es1deYKEQt8ELYFRA',
    appId: '1:869633347200:web:a1612f753352891363a065',
    messagingSenderId: '869633347200',
    projectId: 'inventario-b125a',
    authDomain: 'inventario-b125a.firebaseapp.com',
    storageBucket: 'inventario-b125a.firebasestorage.app',
  );

}